# Permalinks
permalink:           pretty

# Setup
title:               CoderQiang
tagline:             CoderQiang's Blog
url:                 https://qianggeng.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              qiang geng
  url:               https://twitter.com/mdo
  email:             935860278@qq.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/qianggeng/qianggeng.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
